language: python
python:
  - "3.6"
install:
  - pip install -e . --upgrade
  - pip install pipenv --upgrade
  - pipenv install --dev
script:
  - ONS_ENV=travis pipenv run py.test --cov-report term-missing --cov-config=.coveragerc --cov=ras_common_utils/
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
    slack: surveydatacollection:LCbNJJpDoY3gYIvLOlK0nZkV
